# Generated by Django 4.2.4 on 2023-09-04 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TCPLapp", "0002_downloadfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("dob", models.DateField()),
                ("address", models.TextField(max_length=250)),
                ("city", models.TextField(max_length=50)),
                ("pin_code", models.IntegerField()),
                ("mobileno", models.BigIntegerField()),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("others", "others"),
                            ("architect", "architect"),
                            ("builder", "builder"),
                            ("land owner", "land owner"),
                            ("liaison", "liaison"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("civil", "Civil"),
                            ("govt", "Government"),
                            ("private", "Private"),
                            ("ngo", "NGO"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Customer",),
    ]
