# Generated by Django 4.2.4 on 2023-09-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TCPLapp", "0005_villageboundary_delete_elements"),
    ]

    operations = [
        migrations.AlterModelTable(name="villageboundary", table="village_boundary",),
    ]
